import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UserForm from "@/components/UserForm";
import { Box, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Microfrontend 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box mb={5}>
          <h1>Microfrontend 2</h1>
        </Box>
        <Box sx={{ p: 2, border: "1px solid grey" }} mb={2}>
          <Typography variant="body1">Other component not shared</Typography>
        </Box>
        <UserForm />
      </main>
    </>
  );
}
